//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PdfGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Agent Dispatch Report By Location.
        /// </summary>
        internal static string BaDispatchTitle {
            get {
                return ResourceManager.GetString("BaDispatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local 720 Executive Board.
        /// </summary>
        internal static string CcPersonOne {
            get {
                return ResourceManager.GetString("CcPersonOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marielle &apos;Apple&apos; Thorne, Business Representative.
        /// </summary>
        internal static string CcPersonTwo {
            get {
                return ResourceManager.GetString("CcPersonTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via electronically and certified mail. RRR.
        /// </summary>
        internal static string CertifiedStatement {
            get {
                return ResourceManager.GetString("CertifiedStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000 South Valley View Blvd..
        /// </summary>
        internal static string CompanyAddressFirstLine {
            get {
                return ResourceManager.GetString("CompanyAddressFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las Vegas, NV 89178.
        /// </summary>
        internal static string CompanyAddressSecondLine {
            get {
                return ResourceManager.GetString("CompanyAddressSecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CompanyLogo {
            get {
                object obj = ResourceManager.GetObject("CompanyLogo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.iatse720.net.
        /// </summary>
        internal static string CompanyWebsite {
            get {
                return ResourceManager.GetString("CompanyWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely,.
        /// </summary>
        internal static string ComplementaryClose {
            get {
                return ResourceManager.GetString("ComplementaryClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * The referent has not completed the proper training for the requested skill. The required training for this skill is established through the NRA IATSE Local 720 Training Trust manager and the Trustees based on the requirements given them by the employers signatory to IATSE Local 720. Some of this training involves safety aspects of the skill that will help reduce the possibility of on the job injuries. The training for this skill is available and it is recommended that you instruct the referent to obtain t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DispatchWorkerListComment {
            get {
                return ResourceManager.GetString("DispatchWorkerListComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive Board Dispatch Summary Report.
        /// </summary>
        internal static string EbDispatchTitle {
            get {
                return ResourceManager.GetString("EbDispatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Dispatch History By Report Date.
        /// </summary>
        internal static string EmpDispatchTitle {
            get {
                return ResourceManager.GetString("EmpDispatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAX (702) 873-2120.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNATIONAL ALLIANCE OF THEATRICAL STAGE EMPLOYEES,
        ///MOVING PICTURE TECHNICIANS, ARTISTS AND ALLIED CRAFTS OF
        ///THE UNITED STATES, ITS TERRITORIES AND CANADA
        ///AFL-CIO, CLC.
        /// </summary>
        internal static string LetterHeader {
            get {
                return ResourceManager.GetString("LetterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LocalLogo {
            get {
                object obj = ResourceManager.GetObject("LocalLogo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 720.
        /// </summary>
        internal static string MembershipCardIssuer {
            get {
                return ResourceManager.GetString("MembershipCardIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phil Jaynes.
        /// </summary>
        internal static string MembershipCardPresident {
            get {
                return ResourceManager.GetString("MembershipCardPresident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David Weigant.
        /// </summary>
        internal static string MembershipCardSecretary {
            get {
                return ResourceManager.GetString("MembershipCardSecretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las Vegas,.
        /// </summary>
        internal static string MembershipCity {
            get {
                return ResourceManager.GetString("MembershipCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevada.
        /// </summary>
        internal static string MembershipState {
            get {
                return ResourceManager.GetString("MembershipState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property of IATSE Local 720.
        /// </summary>
        internal static string PropertyMsg {
            get {
                return ResourceManager.GetString("PropertyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone (702) 873-3450.
        /// </summary>
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
    }
}
